version: '3.8'

services:

  web:
    container_name: homies
    image: braynovhomiescr11.azurecr.io/homies
    domainname: braynov
    ports:
      - "80:80"
    restart: on-failure

  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server
    ports: 
        - "1433:1433"
    deploy:
        resources:
            reservations:
                cpus: '2'
                memory: 2GB
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=myStrongPassword12#
    volumes: 
        - sqldata:/var/opt/mssql

volumes:
    sqldata:
        driver: azure_file
        driver_opts:
            share_name: sql-volume11
            storage_account_name: homiesstorageaccbr11
